[[TempestModel]]
arch = "x86_64"
git-tree-sha1 = "acff986024fd2d8fc10f1c605899cac76d52ae63"
lazy = true
mpi = "mpich"
os = "macos"

    [[TempestModel.download]]
    sha256 = "67196fbaebb4348b6dc38c642a4d918e9dec7a774848595567141319cd6d68a6"
    url = "https://github.com/JuliaBinaryWrappers/TempestModel_jll.jl/releases/download/TempestModel-v0.1.1+0/TempestModel.v0.1.1.x86_64-apple-darwin-mpi+mpich.tar.gz"
[[TempestModel]]
arch = "x86_64"
git-tree-sha1 = "c79c50c42058794feb8cc2ca5373fc5832ac27a4"
lazy = true
mpi = "mpitrampoline"
os = "macos"

    [[TempestModel.download]]
    sha256 = "9f042776579dc8758116aeefb62ed04015aa97cb4ebf772b357903755cbfa8c1"
    url = "https://github.com/JuliaBinaryWrappers/TempestModel_jll.jl/releases/download/TempestModel-v0.1.1+0/TempestModel.v0.1.1.x86_64-apple-darwin-mpi+mpitrampoline.tar.gz"
[[TempestModel]]
arch = "x86_64"
git-tree-sha1 = "bd4fc981c3ef6231af3a6a0216930dc18219a5c5"
lazy = true
mpi = "openmpi"
os = "macos"

    [[TempestModel.download]]
    sha256 = "bb470798cc45026147f90615adda85ada09318e42798c1363f29108baa7627e3"
    url = "https://github.com/JuliaBinaryWrappers/TempestModel_jll.jl/releases/download/TempestModel-v0.1.1+0/TempestModel.v0.1.1.x86_64-apple-darwin-mpi+openmpi.tar.gz"
[[TempestModel]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "d5887ca0264da29cc5ded5dae36d3cb648e0aab8"
lazy = true
libc = "glibc"
mpi = "mpich"
os = "linux"

    [[TempestModel.download]]
    sha256 = "321bde8a73142d2ffd3166f56edaab9f8df98e8d24c6504f62aa6ececb85eea7"
    url = "https://github.com/JuliaBinaryWrappers/TempestModel_jll.jl/releases/download/TempestModel-v0.1.1+0/TempestModel.v0.1.1.x86_64-linux-gnu-cxx03-mpi+mpich.tar.gz"
[[TempestModel]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "21d91a20d7ddf68aa38238c22c06e285bb299edf"
lazy = true
libc = "glibc"
mpi = "mpitrampoline"
os = "linux"

    [[TempestModel.download]]
    sha256 = "c3046fce2e18a14891bb65e44baa60b6a1c5b6ede5b65c830845b45162245775"
    url = "https://github.com/JuliaBinaryWrappers/TempestModel_jll.jl/releases/download/TempestModel-v0.1.1+0/TempestModel.v0.1.1.x86_64-linux-gnu-cxx03-mpi+mpitrampoline.tar.gz"
[[TempestModel]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "4cf957a9a0ac9f19d70a31a498c742f6a792f40e"
lazy = true
libc = "glibc"
mpi = "openmpi"
os = "linux"

    [[TempestModel.download]]
    sha256 = "a8e16a20bcfd4ac3fd7bbb501717c647a4fd6c24fc0c1c15f6b6f6898b5469ff"
    url = "https://github.com/JuliaBinaryWrappers/TempestModel_jll.jl/releases/download/TempestModel-v0.1.1+0/TempestModel.v0.1.1.x86_64-linux-gnu-cxx03-mpi+openmpi.tar.gz"
[[TempestModel]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "08bad6c99a4f9b1c9ea2b7b2ef860bd034dac28d"
lazy = true
libc = "glibc"
mpi = "mpich"
os = "linux"

    [[TempestModel.download]]
    sha256 = "98180d2239ae8eeb6242173d58d6d3dbd90650cbee5ff4040b742e7b017a3811"
    url = "https://github.com/JuliaBinaryWrappers/TempestModel_jll.jl/releases/download/TempestModel-v0.1.1+0/TempestModel.v0.1.1.x86_64-linux-gnu-cxx11-mpi+mpich.tar.gz"
[[TempestModel]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "62114d0e84da4bc24c887157cdc95c554e923d8c"
lazy = true
libc = "glibc"
mpi = "mpitrampoline"
os = "linux"

    [[TempestModel.download]]
    sha256 = "88d9759acb23fa9f2b51514ecc26e0a67f4fa9ac2f239c54b8e3329e5dd2134c"
    url = "https://github.com/JuliaBinaryWrappers/TempestModel_jll.jl/releases/download/TempestModel-v0.1.1+0/TempestModel.v0.1.1.x86_64-linux-gnu-cxx11-mpi+mpitrampoline.tar.gz"
[[TempestModel]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "c643995b8629018e5aacc89e7f139ac86e0ddc93"
lazy = true
libc = "glibc"
mpi = "openmpi"
os = "linux"

    [[TempestModel.download]]
    sha256 = "847014b1f64a861c9053173b1fb3eb4f1d6f3779b10821d4a2ce5128623ce39f"
    url = "https://github.com/JuliaBinaryWrappers/TempestModel_jll.jl/releases/download/TempestModel-v0.1.1+0/TempestModel.v0.1.1.x86_64-linux-gnu-cxx11-mpi+openmpi.tar.gz"
