# Autogenerated wrapper script for TempestModel_jll for x86_64-linux-gnu-cxx11-mpi+openmpi
export BaldaufGravityWaveTest_exe, Baroclinic3DCartesianRidgeTest_exe, Baroclinic3DCartesianTest_exe, BaroclinicWaveJWTest_exe, BaroclinicWaveUMJSTest_exe, BarotropicInstabilityTest_exe, DensityCurrentCartesianTest_exe, HeldSuarezTest_exe, HydrostaticMountainCartesianTest_exe, InertiaGravityWaveTest_exe, InertialGravityCartesianXZTest_exe, MountainRossby3DTest_exe, MountainRossbyTest_exe, MountainWaveSphereTest_exe, NonHydroMountainCartesianTest_exe, RobertBubbleCartesianTest_exe, RossbyHaurwitzWaveTest_exe, ScharMountainCartesianTest_exe, ScharMountainSphereTest_exe, ShearJetMtnWave2DCartesianTest_exe, StationaryMountainFlowTest_exe, ThermalBubbleCartesian3DTest_exe, ThermalBubbleCartesianTest_exe

using MKL_jll
using NetCDF_jll
using HDF5_jll
using OpenMPI_jll
using MPIPreferences
JLLWrappers.@generate_wrapper_header("TempestModel")
JLLWrappers.@declare_executable_product(BaldaufGravityWaveTest_exe)
JLLWrappers.@declare_executable_product(Baroclinic3DCartesianRidgeTest_exe)
JLLWrappers.@declare_executable_product(Baroclinic3DCartesianTest_exe)
JLLWrappers.@declare_executable_product(BaroclinicWaveJWTest_exe)
JLLWrappers.@declare_executable_product(BaroclinicWaveUMJSTest_exe)
JLLWrappers.@declare_executable_product(BarotropicInstabilityTest_exe)
JLLWrappers.@declare_executable_product(DensityCurrentCartesianTest_exe)
JLLWrappers.@declare_executable_product(HeldSuarezTest_exe)
JLLWrappers.@declare_executable_product(HydrostaticMountainCartesianTest_exe)
JLLWrappers.@declare_executable_product(InertiaGravityWaveTest_exe)
JLLWrappers.@declare_executable_product(InertialGravityCartesianXZTest_exe)
JLLWrappers.@declare_executable_product(MountainRossby3DTest_exe)
JLLWrappers.@declare_executable_product(MountainRossbyTest_exe)
JLLWrappers.@declare_executable_product(MountainWaveSphereTest_exe)
JLLWrappers.@declare_executable_product(NonHydroMountainCartesianTest_exe)
JLLWrappers.@declare_executable_product(RobertBubbleCartesianTest_exe)
JLLWrappers.@declare_executable_product(RossbyHaurwitzWaveTest_exe)
JLLWrappers.@declare_executable_product(ScharMountainCartesianTest_exe)
JLLWrappers.@declare_executable_product(ScharMountainSphereTest_exe)
JLLWrappers.@declare_executable_product(ShearJetMtnWave2DCartesianTest_exe)
JLLWrappers.@declare_executable_product(StationaryMountainFlowTest_exe)
JLLWrappers.@declare_executable_product(ThermalBubbleCartesian3DTest_exe)
JLLWrappers.@declare_executable_product(ThermalBubbleCartesianTest_exe)
function __init__()
    JLLWrappers.@generate_init_header(MKL_jll, NetCDF_jll, HDF5_jll, OpenMPI_jll, MPIPreferences)
    JLLWrappers.@init_executable_product(
        BaldaufGravityWaveTest_exe,
        "bin/BaldaufGravityWaveTest",
    )

    JLLWrappers.@init_executable_product(
        Baroclinic3DCartesianRidgeTest_exe,
        "bin/Baroclinic3DCartesianRidgeTest",
    )

    JLLWrappers.@init_executable_product(
        Baroclinic3DCartesianTest_exe,
        "bin/Baroclinic3DCartesianTest",
    )

    JLLWrappers.@init_executable_product(
        BaroclinicWaveJWTest_exe,
        "bin/BaroclinicWaveJWTest",
    )

    JLLWrappers.@init_executable_product(
        BaroclinicWaveUMJSTest_exe,
        "bin/BaroclinicWaveUMJSTest",
    )

    JLLWrappers.@init_executable_product(
        BarotropicInstabilityTest_exe,
        "bin/BarotropicInstabilityTest",
    )

    JLLWrappers.@init_executable_product(
        DensityCurrentCartesianTest_exe,
        "bin/DensityCurrentCartesianTest",
    )

    JLLWrappers.@init_executable_product(
        HeldSuarezTest_exe,
        "bin/HeldSuarezTest",
    )

    JLLWrappers.@init_executable_product(
        HydrostaticMountainCartesianTest_exe,
        "bin/HydrostaticMountainCartesianTest",
    )

    JLLWrappers.@init_executable_product(
        InertiaGravityWaveTest_exe,
        "bin/InertiaGravityWaveTest",
    )

    JLLWrappers.@init_executable_product(
        InertialGravityCartesianXZTest_exe,
        "bin/InertialGravityCartesianXZTest",
    )

    JLLWrappers.@init_executable_product(
        MountainRossby3DTest_exe,
        "bin/MountainRossby3DTest",
    )

    JLLWrappers.@init_executable_product(
        MountainRossbyTest_exe,
        "bin/MountainRossbyTest",
    )

    JLLWrappers.@init_executable_product(
        MountainWaveSphereTest_exe,
        "bin/MountainWaveSphereTest",
    )

    JLLWrappers.@init_executable_product(
        NonHydroMountainCartesianTest_exe,
        "bin/NonHydroMountainCartesianTest",
    )

    JLLWrappers.@init_executable_product(
        RobertBubbleCartesianTest_exe,
        "bin/RobertBubbleCartesianTest",
    )

    JLLWrappers.@init_executable_product(
        RossbyHaurwitzWaveTest_exe,
        "bin/RossbyHaurwitzWaveTest",
    )

    JLLWrappers.@init_executable_product(
        ScharMountainCartesianTest_exe,
        "bin/ScharMountainCartesianTest",
    )

    JLLWrappers.@init_executable_product(
        ScharMountainSphereTest_exe,
        "bin/ScharMountainSphereTest",
    )

    JLLWrappers.@init_executable_product(
        ShearJetMtnWave2DCartesianTest_exe,
        "bin/ShearJetMtnWave2DCartesianTest",
    )

    JLLWrappers.@init_executable_product(
        StationaryMountainFlowTest_exe,
        "bin/StationaryMountainFlowTest",
    )

    JLLWrappers.@init_executable_product(
        ThermalBubbleCartesian3DTest_exe,
        "bin/ThermalBubbleCartesian3DTest",
    )

    JLLWrappers.@init_executable_product(
        ThermalBubbleCartesianTest_exe,
        "bin/ThermalBubbleCartesianTest",
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
